
RDocumentation 
R Enterprise Training
R package
Leaderboard
Sign in
 
getTrends
From twitteR v1.1.9
by Jeff Gentry
99.99th
Percentile
Functions to view Twitter trends 
These functions will allow you to interact with the trend portion of the Twitter API 
Keywords
interface
Usage
availableTrendLocations(...) closestTrendLocations(lat, long, ...) getTrends(woeid, exclude=NULL, ...)
Arguments
woeid
A numerical identification code describing a location, a Yahoo! Where On Earth ID
lat
A numerical latitude value, between -180 and 180 inclusive. West is negative, East is positive
long
A numerical longitude value, between -180 and 180 inclusive. South is negative, North is positive
exclude
If set to hashtags, will exclude hashtags
...
Additional arguments to be passed to RCurl
Details
The availableTrendLocations and closestTrendLocations functions will return a data.frame with three columns - name, country and woeid. The closestTrendLocations function will return the locations closest to the specified latitude and longitude. The getTrends function takes a specified woeid and returns the trending topics associated with that woeid. It returns a data.frame with the columns being name, url, promoted_content, query and woeid - one row per trend. 
Value

A data.frame with the columns specified in Details above 

Examples
  ## Not run: 
#     woeid = availableTrendLocations[1, "woeid"]
#     t1 <- getTrends(woeid)
#   ## End(Not run)
Documentation reproduced from package twitteR, version 1.1.9, License: Artistic-2.0 
Community examples
Looks like there are no examples yet.
Post a new example:
|||||

## New example
Use markdown to format your example

R code blocks are runnable and interactive:
```r
a <- 2
print(a)
```

You can also display normal code blocks
```
var a = b
```

​

Submit your example
 API documentation 
R package 
Rdocumentation.org 
Created by DataCamp.com
Learn R at work Try it free 
